[package]
name = "docz-ast-epub"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
epub-builder = "0.7.4"
docz-ast = { version = "0.1.0", path = "../docz-ast" }
