[package]
name = "docz-lib"
version = "0.1.0"
edition = "2021"
description = "Doc generation library for CLI"
license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/docz-lib"
repository = "https://github.com/nlargueze/docz.git"

[features]
default = ["mkd"]
mkd = ["pulldown-cmark"]

[dependencies]
anyhow = "1.0.72"
log = "0.4.19"
pulldown-cmark = { version = "0.9.3", optional = true }
serde = { version = "1.0.182", features = ["derive"] }
toml = "0.7.6"
