[doc]
title = "Doc title"
description = "Doc description"
authors = []

[src]
src_dir = "src"
assets_dir = "_assets"

[build]
build_dir = "build"

[watch]
extra_dirs = ["tpl"]

[output.debug]

[output.html]
template = "default"
# index = "tpl/index.hbs"
static_files = [["tpl/style.css", "style.css"]]
