[package]
name = "docz-ast-pdf"
version = "0.1.0"
edition = "2021"

[dependencies]
docz-ast = { version = "0.1.0", path = "../docz-ast" }
printpdf = { version = "0.5.3", features = ["image"] }
textwrap = "0.16.0"
thiserror = "1.0.44"
