[package]
name = "docz-ast"
version = "0.1.0"
edition = "2021"
description = "Generic AST for docz"

[dependencies]
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
thiserror = "1.0.44"
